spring:
  security:
    oauth2:
      client:
        registration:
            spotify:
              client-id: ${CLIENT_ID}
              client-secret: ${CLIENT_SECRET}
              scope: playlist-read-private, user-read-currently-playing, user-follow-read, user-top-read
              authorization-grant-type: authorization_code
              client-authentication-method: client_secret_basic
              redirect-uri: "{baseUrl}/login/oauth2/code/spotify"
              provider: spotify
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            api-uri: https://api.spotify.com/v1
            user-name-attribute: id

# More detailed security log
#logging:
#  level:
#    org:
#      springframework:
#        security: TRACE

  datasource:
    url: jdbc:h2:file:./data/spotifyUsers
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect

app:
  jwtSecret: ${JWT_ENCODED}
  jwtExpirationMs: ${MILLISECONDS}
  frontend:
    redirectUrl: ${FRONTEND_URL_REDIRECT}

server:
  port: 8080